language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

gemfile:
  - Gemfile

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rubocop
  - bundle exec rake

branches:
  only:
    - master
